report 50091 "Revenue Generated by SA"
{
    DefaultLayout = RDLC;
    RDLCLayout = './RevenueGeneratedbySA.rdlc';

    dataset
    {
        dataitem(DataItem5; Table5992)
        {
            column(PostingDate_ServiceInvoiceHeader; "Service Invoice Header"."Posting Date")
            {
            }
            column(CustomerNo_ServiceInvoiceHeader; "Service Invoice Header"."Customer No.")
            {
            }
            column(No_ServiceInvoiceHeader; "Service Invoice Header"."No.")
            {
            }
            column(AmountGenerated; AMountGen)
            {
            }
            column(NoOfJobs; NoOfJobs)
            {
            }
            column(SalesPerson; SalesPersonName)
            {
            }
            column(TotalLineAmount_ServiceInvoiceHeader; "Service Invoice Header"."Total Line Amount")
            {
            }
            column(StartDate; StartDate)
            {
            }
            column(Enddate; EndDate)
            {
            }

            trigger OnAfterGetRecord()
            begin
                ServiceInvoiceHeader.SETRANGE("Posting Date", StartDate, EndDate);


                SalespersonPurchaser.GET("Salesperson Code");
                SalesPersonName := SalespersonPurchaser.Name;
            end;
        }
    }

    requestpage
    {

        layout
        {
            area(content)
            {
                field("Start Date"; StartDate)
                {
                }
                field("End Date"; EndDate)
                {
                }
            }
        }

        actions
        {
        }
    }

    labels
    {
    }

    var
        NoOfJobs: Integer;
        AMountGen: Decimal;
        StartDate: Date;
        EndDate: Date;
        ServiceInvoiceHeader: Record "5992";
        SalespersonPurchaser: Record "13";
        SalesPersonName: Text;
}

