page 80000 "Service Adviser Role Center"
{
    Caption = 'Role Center';
    PageType = RoleCenter;

    layout
    {
        area(rolecenter)
        {
            group()
            {
                part(; 80001)
                {
                }
            }
            group()
            {
                part(; 675)
                {
                    Visible = false;
                }
                part(; 9150)
                {
                }
                part(; 681)
                {
                    Visible = false;
                }
                systempart(; MyNotes)
                {
                }
            }
        }
    }

    actions
    {
        area(reporting)
        {
            action("Service &Order")
            {
                Caption = 'Service &Order';
                Image = Document;
                RunObject = Report 5900;
            }
            action("Service Item &Line Labels")
            {
                Caption = 'Service Item &Line Labels';
                Image = "Report";
                RunObject = Report 5901;
            }
            action("Service &Item Worksheet")
            {
                Caption = 'Service &Item Worksheet';
                Image = ServiceItemWorksheet;
                RunObject = Report 5936;
            }
            action("Spare Part Used in the Workshop")
            {
                Caption = 'Spare Part Used in the Workshop';
                Image = ItemTrackingLedger;
                Promoted = false;
                //The property 'PromotedCategory' can only be set if the property 'Promoted' is set to 'true'
                //PromotedCategory = "Report";
                //The property 'PromotedIsBig' can only be set if the property 'Promoted' is set to 'true'
                //PromotedIsBig = true;
                RunObject = Report 50092;
            }
            action("Revenue Generated By SA")
            {
                Image = JobLedger;
                Promoted = false;
                //The property 'PromotedCategory' can only be set if the property 'Promoted' is set to 'true'
                //PromotedCategory = "Report";
                //The property 'PromotedIsBig' can only be set if the property 'Promoted' is set to 'true'
                //PromotedIsBig = true;
                RunObject = Report 50091;
            }
            action("Delivered Customer Order List")
            {
                Caption = 'Closed Jobs';
                RunObject = Page 80052;
            }
            action("WIP Customer Order List")
            {
                Caption = 'Opened Jobs';
                RunObject = Page 80043;
                RunPageView = WHERE (Service Location=FILTER(120ISO));
            }
            action("Transfer History")
            {
                RunObject = Page 70511;
            }
            action("TNL sales Contribution")
            {
                RunObject = Report 50184;
            }
            action("Posted Service Invoice Line")
            {
                Caption = 'Posted Service Item/Cost';
                RunObject = Report 50054;
            }
            action("Technicians Hours ")
            {
                Caption = 'Technicians Hours ';
                RunObject = Report 50053;
            }
            action("Posted Service Invoice GR,PM,BP")
            {
                Caption = 'Posted Service Invoice/Document';
                RunObject = Page 80071;
            }
            action("TCSC posted slaes line")
            {
                RunObject = Page 80062;
            }
            action(GR)
            {
                RunObject = Report 50055;
            }
            action("COF Summary Report")
            {
                Caption = 'COF Summary Report';
                Image = BulletList;
                Promoted = true;
                PromotedCategory = "Report";
                PromotedIsBig = true;
                RunObject = Report 50319;
            }
            action("Posted GR Jobs")
            {
                RunObject = Page 80064;
            }
            action("Posted B&P Jobs")
            {
                RunObject = Page 80066;
            }
            action("Posted PM Jobs")
            {
                RunObject = Page 80069;
            }
        }
        area(embedding)
        {
            action(Inventory)
            {
                Caption = 'Inventory';
                Image = List;
                RunObject = Page 31;
            }
            action("Service Item")
            {
                RunObject = Page 5981;
            }
            action("POS Receipt")
            {
                RunObject = Page 70005;
            }
            action("Leave Request")
            {
                RunObject = Page 50604;
            }
            action("Approval Leave")
            {
                RunObject = Page 50609;
            }
            action("Approved Leave")
            {
                RunObject = Page 50608;
            }
            action("Transfer Order")
            {
                RunObject = Page 5742;
            }
            action("IOU Register")
            {
                RunObject = Page 70030;
            }
            action("Service Invoice List")
            {
                RunObject = Page 9319;
            }
            action("Service Order List")
            {
                RunObject = Page 9318;
            }
            action("Posted Service Invoices")
            {
                RunObject = Page 5977;
            }
            action("TCSC Items")
            {
                Caption = 'TCSC Items';
                RunObject = Page 70176;
            }
            action("TCSC Customers")
            {
                Caption = 'TCSC Customers';
                RunObject = Page 70175;
            }
            action("Maintenance Reminder Today")
            {
                Caption = 'Maintenance Reminder Today';
                RunObject = Page 80039;
            }
        }
        area(sections)
        {
        }
        area(creation)
        {
            action("Service &Order")
            {
                Caption = 'Service &Order';
                Image = Document;
                Promoted = false;
                //The property 'PromotedCategory' can only be set if the property 'Promoted' is set to 'true'
                //PromotedCategory = Process;
                RunObject = Page 5900;
                                RunPageMode = Create;
            }
            action("&Loaner")
            {
                Caption = '&Loaner';
                Image = Loaner;
                Promoted = false;
                //The property 'PromotedCategory' can only be set if the property 'Promoted' is set to 'true'
                //PromotedCategory = Process;
                RunObject = Page 5922;
                                RunPageMode = Create;
            }
        }
        area(processing)
        {
            separator(Tasks)
            {
                Caption = 'Tasks';
                IsHeader = true;
            }
            action("Service Item &Worksheet")
            {
                Caption = 'Service Item &Worksheet';
                Image = ServiceItemWorksheet;
                RunObject = Page 5906;
            }
            group("Payment Process")
            {
                Caption = 'Payment Process';
                Image = Journals;
                action("Journal Voucher")
                {
                    Caption = 'Journal Voucher';
                    RunObject = Page 70011;
                }
                action("IOU Request")
                {
                    RunObject = Page 70030;
                }
                action("IOU Approved")
                {
                    RunObject = Page 70032;
                }
                action("IOU Treated")
                {
                    RunObject = Page 50217;
                }
                action("IOU Retirement")
                {
                    RunObject = Page 50204;
                }
                action("IOU Retirement Approved")
                {
                    RunObject = Page 70033;
                }
                action("Posted IOU Retirement")
                {
                    RunObject = Page 70034;
                }
            }
            group(Procurement)
            {
                Caption = 'Procurement';
                Image = ReferenceData;
                action(Opex)
                {
                    Caption = 'Opex';
                    RunObject = Page 70125;
                }
                action("Head of Dept. Appr.")
                {
                    Caption = 'Head of Dept. Appr.Opex';
                    RunObject = Page 70131;
                }
                action("Head of Audit  Appr.")
                {
                    Caption = 'Head of Audit Appr.Opex';
                    RunObject = Page 70129;
                }
                action("Approved Opex")
                {
                    Caption = 'Approved Opex';
                    RunObject = Page 70134;
                }
                action("Advance payment")
                {
                    Caption = 'Advance payment Opex';
                    RunObject = Page 70135;
                }
                action("Advanced Payment Approved-Opex")
                {
                    Caption = 'Advanced Payment Approved-Opex';
                    RunObject = Page 70145;
                }
                action("Compliance Check")
                {
                    Caption = 'Compliance Check Opex';
                    RunObject = Page 70138;
                }
                action("Awaiting balance Payment")
                {
                    RunObject = Page 70148;
                }
                action("Balance Payment Appr.")
                {
                    Caption = 'Balance Payment Appr. Opex';
                    RunObject = Page 70139;
                }
                action("LPO-Opex")
                {
                    Caption = 'LPO-Opex';
                    RunObject = Page 70142;
                }
                action("Balance/Full Payment Approved")
                {
                    Caption = 'Balance/Full Payment Approved Opex';
                    RunObject = Page 70140;
                }
                action("Balance/Full Payment Opex-MD")
                {
                    Caption = 'Balance/Full Payment Opex-MD';
                    RunObject = Page 70186;
                }
                action("Balance/full Payment Opex- GM")
                {
                    Caption = 'Balance/Full Payment Opex GM';
                    RunObject = Page 70187;
                }
                action(Capex)
                {
                    Caption = 'Capex';
                    Image = Item;
                    RunObject = Page 70118;
                }
                action("Head of Dept. Appr.Capex")
                {
                    Caption = 'Head of Dept. Appr. Capex';
                    RunObject = Page 70155;
                }
                action("Head of Audit Appr.-Capex")
                {
                    Caption = 'Head of Audit Appr.-Capex';
                    RunObject = Page 70154;
                }
                action("Gen. Manager Appr.-Capex")
                {
                    Caption = 'Gen. Manager Appr.-Capex';
                    RunObject = Page 70156;
                }
                action("Managing Dir. Appr.-Capex")
                {
                    Caption = 'Managing Dir. Appr.-Capex';
                    RunObject = Page 70157;
                }
                action("Move to LPO -Capex")
                {
                    Caption = 'Move to LPO -Capex';
                    RunObject = Page 70158;
                }
                action("Compliance Check-Capex")
                {
                    Caption = 'Compliance Check-Capex';
                    RunObject = Page 70161;
                }
                action("Advance Paymt Appr.-Capex")
                {
                    RunObject = Page 70159;
                }
                action("Awaiting Balance Payment-Capex")
                {
                    RunObject = Page 70167;
                }
                action("Full  Payment Appr.-Capex")
                {
                    Caption = 'Full  Payment Appr.-Capex';
                    RunObject = Page 70162;
                }
                action("LPO-Capex")
                {
                    Caption = 'LPO-Capex';
                    RunObject = Page 70165;
                }
            }
        }
    }
}

